"""Update Playlist model

Revision ID: 79287f54cf5c
Revises: 2be106e099ea
Create Date: 2026-03-05 21:29:08.266919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79287f54cf5c'
down_revision = '2be106e099ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coverUrl', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlist', schema=None) as batch_op:
        batch_op.drop_column('coverUrl')

    # ### end Alembic commands ###
